### ISSUE TITLE
Add subscription route for GCM service

### ISSUE THREAD

**Issue by christian-fei** [christian-fei/pomodoro-api#2]
- [x] POST /api/subscription
- [x] accepts JSON in the form `{"username":"abc"}`
- [x] saves user in subscriptions collection

#### TODO
- security
- differentiate subscriptions by username && service
